export type Product = {
  id: string;
  name: string;
  slug: string;
  price: number;
  unit: string;
  category: string;
  accent: string;
  imagePath: string;
  imageAlt: string;
  description: string;
  shortDescription: string;
  rating: number;
  reviewCount: number;
  tags: string[];
  specs: Array<{ label: string; value: string }>;
};

export type ProductDetailContent = {
  gallery: string[];
  summary: string[];
  description: string;
  uses: string;
  usage: string;
  cautions: string;
  storage: string;
};

export const products: Product[] = [
  {
    id: "omron-hvf013",
    name: "Máy massage xung điện trị liệu Omron HV-F013",
    slug: "may-massage-omron-hv-f013",
    price: 1200000,
    unit: "Hộp",
    category: "Thiết bị hỗ trợ trị liệu",
    accent: "#8caecc",
    imagePath: "/omron_main.webp",
    imageAlt: "Máy massage xung điện Omron HV-F013",
    description:
      "Thiết bị trị liệu xung điện nhỏ gọn, phù hợp chăm sóc cơ bắp và phục hồi tại nhà.",
    shortDescription: "Máy massage xung điện gọn nhẹ hỗ trợ giảm đau cơ và khớp.",
    rating: 4.8,
    reviewCount: 128,
    tags: ["massage", "trị liệu", "omron"],
    specs: [
      { label: "Thương hiệu", value: "Omron" },
      { label: "Loại", value: "Thiết bị massage xung điện" },
      { label: "Phù hợp", value: "Gia đình, người đau cơ khớp" },
      { label: "Bảo hành", value: "24 tháng" },
    ],
  },
  {
    id: "greentec-mask",
    name: "Mặt nạ xông khí dung Greentec nebulizer mask size M",
    slug: "mat-na-khi-dung-greentec-mask-size-m",
    price: 21000,
    unit: "Cái",
    category: "Phụ kiện khí dung",
    accent: "#85e6f4",
    imagePath: "/greatmed_main.webp",
    imageAlt: "Mặt nạ xông khí dung Greentec size M",
    description:
      "Mặt nạ khí dung chất liệu mềm, bám ôm tốt, dùng kèm máy xông cho cả người lớn.",
    shortDescription: "Phụ kiện khí dung ôm mặt, chất liệu mềm và dễ vệ sinh.",
    rating: 4.6,
    reviewCount: 52,
    tags: ["khí dung", "phụ kiện", "greentec"],
    specs: [
      { label: "Kích cỡ", value: "Size M" },
      { label: "Chất liệu", value: "Nhựa y tế mềm" },
      { label: "Phù hợp", value: "Người lớn" },
      { label: "Đóng gói", value: "1 cái / túi" },
    ],
  },
  {
    id: "pic-insupen",
    name: "Đầu kim tiểu đường 33G x 4mm Pic Insupen",
    slug: "dau-kim-tieu-duong-pic-insupen-33g-4mm",
    price: 250000,
    unit: "Hộp",
    category: "Chăm sóc tiểu đường",
    accent: "#f5ca5e",
    imagePath: "/DSC_main.webp",
    imageAlt: "Đầu kim tiểu đường Pic Insupen 33G x 4mm",
    description:
      "Đầu kim vô trùng siêu mảnh, giảm đau khi sử dụng và tương thích với nhiều bút tiêm insulin.",
    shortDescription: "Đầu kim vô trùng siêu mảnh cho người dùng insulin mỗi ngày.",
    rating: 4.9,
    reviewCount: 93,
    tags: ["tiểu đường", "insulin", "pic"],
    specs: [
      { label: "Kích cỡ kim", value: "33G x 4mm" },
      { label: "Ứng dụng", value: "Bút tiêm insulin" },
      { label: "Đặc điểm", value: "Siêu mảnh, giảm đau" },
      { label: "Đóng gói", value: "100 kim / hộp" },
    ],
  },
  {
    id: "yuwell-ye610d",
    name: "Máy đo huyết áp bắp tay Yuwell YE610D",
    slug: "may-do-huyet-ap-yuwell-ye610d",
    price: 699000,
    unit: "Hộp",
    category: "Máy đo huyết áp",
    accent: "#d7dfe7",
    imagePath: "/TUK_1.webp",
    imageAlt: "Máy đo huyết áp bắp tay Yuwell YE610D",
    description:
      "Máy đo huyết áp điện tử có màn hình lớn, ghi nhớ kết quả và cảnh báo nhịp tim bất thường.",
    shortDescription: "Máy đo huyết áp điện tử màn hình lớn, dễ dùng cho gia đình.",
    rating: 4.7,
    reviewCount: 184,
    tags: ["huyết áp", "yuwell", "điện tử"],
    specs: [
      { label: "Vị trí đo", value: "Bắp tay" },
      { label: "Màn hình", value: "LCD lớn" },
      { label: "Tính năng", value: "Nhớ kết quả, cảnh báo nhịp tim" },
      { label: "Nguồn", value: "Pin / Adapter" },
    ],
  },
  {
    id: "infrared-nc1",
    name: "Nhiệt kế hồng ngoại đo trán Yuwell YT-1C",
    slug: "nhiet-ke-hong-ngoai-yuwell-yt1c",
    price: 501500,
    unit: "Hộp",
    category: "Nhiệt kế",
    accent: "#dfe7ee",
    imagePath: "/NKHN_main.webp",
    imageAlt: "Nhiệt kế hồng ngoại Yuwell YT-1C",
    description:
      "Nhiệt kế không chạm cho kết quả nhanh, phù hợp gia đình có trẻ nhỏ và người lớn tuổi.",
    shortDescription: "Nhiệt kế hồng ngoại đo nhanh, không chạm, dùng thuận tiện tại nhà.",
    rating: 4.6,
    reviewCount: 76,
    tags: ["nhiệt kế", "hồng ngoại", "yuwell"],
    specs: [
      { label: "Kiểu đo", value: "Không chạm" },
      { label: "Thời gian trả kết quả", value: "1 giây" },
      { label: "Đối tượng", value: "Trẻ em, người lớn" },
      { label: "Nguồn", value: "Pin AAA" },
    ],
  },
  {
    id: "lancet-medi",
    name: "Kim lấy máu Lancet Medicleen BL-28",
    slug: "kim-lay-mau-lancet-medicleen-bl28",
    price: 32000,
    unit: "Hộp",
    category: "Tiêu hao y tế",
    accent: "#8ea8d2",
    imagePath: "/KLM_main.webp",
    imageAlt: "Kim lấy máu Lancet Medicleen BL-28",
    description:
      "Kim lấy máu vô trùng sử dụng một lần, hỗ trợ lấy mẫu nhanh và hạn chế đau rát.",
    shortDescription: "Kim lấy máu dùng một lần, hỗ trợ lấy mẫu nhanh và an toàn.",
    rating: 4.5,
    reviewCount: 41,
    tags: ["lancet", "lấy máu", "tiêu hao"],
    specs: [
      { label: "Chuẩn kim", value: "BL-28" },
      { label: "Mục đích", value: "Lấy mẫu máu mao mạch" },
      { label: "Đặc điểm", value: "Vô trùng, dùng một lần" },
      { label: "Đóng gói", value: "100 chiếc / hộp" },
    ],
  },
  {
    id: "braun-22g",
    name: "Kim luồn tĩnh mạch Braun 22G",
    slug: "kim-luon-tinh-mach-braun-22g",
    price: 19000,
    unit: "Cái",
    category: "Tiêu hao y tế",
    accent: "#dce8f5",
    imagePath: "/Braun_1.webp",
    imageAlt: "Kim luồn tĩnh mạch Braun 22G",
    description:
      "Kim luồn tĩnh mạch dùng trong hỗ trợ truyền dịch, đảm bảo vô trùng và thao tác thuận tiện.",
    shortDescription: "Kim luồn tĩnh mạch hỗ trợ truyền dịch, nước vào cơ thể.",
    rating: 4.4,
    reviewCount: 32,
    tags: ["kim luồn", "braun", "truyền dịch"],
    specs: [
      { label: "Kích cỡ", value: "22G" },
      { label: "Loại", value: "Vô trùng, dùng một lần" },
      { label: "Ứng dụng", value: "Truyền dịch ngoại vi" },
      { label: "Đóng gói", value: "1 cái / túi" },
    ],
  },
  {
    id: "accu-chek-instant",
    name: "Máy đo đường huyết Accu-Chek Instant",
    slug: "may-do-duong-huyet-accu-chek-instant",
    price: 850000,
    unit: "Hộp",
    category: "Chăm sóc tiểu đường",
    accent: "#d7ecff",
    imagePath: "/Accu_main.webp",
    imageAlt: "Máy đo đường huyết Accu-Chek Instant",
    description:
      "Máy đo đường huyết màn hình rõ nét, cho kết quả nhanh, hỗ trợ người bệnh theo dõi đường huyết tại nhà.",
    shortDescription: "Máy đo đường huyết tiện dùng để kiểm soát lượng đường trong máu.",
    rating: 4.9,
    reviewCount: 210,
    tags: ["đường huyết", "accu-chek", "tiểu đường"],
    specs: [
      { label: "Thương hiệu", value: "Accu-Chek" },
      { label: "Kết quả", value: "Nhanh, dễ đọc" },
      { label: "Màn hình", value: "LCD lớn" },
      { label: "Tính năng", value: "Theo dõi tại nhà" },
    ],
  },
  {
    id: "greetmed-butterfly-22g",
    name: "Dây truyền dịch kim bướm Greetmed 22G",
    slug: "day-truyen-dich-kim-buom-greetmed-22g",
    price: 5000,
    unit: "Cái",
    category: "Tiêu hao y tế",
    accent: "#eff5fb",
    imagePath: "/DTD_main.webp",
    imageAlt: "Dây truyền dịch kim bướm Greetmed 22G",
    description:
      "Dây truyền dịch kim bướm vô trùng, thường dùng trong truyền dịch ngắn hạn và lấy ven ngoại vi.",
    shortDescription: "Dây truyền dịch kim bướm dùng để truyền dịch cho bệnh nhân.",
    rating: 4.3,
    reviewCount: 15,
    tags: ["truyền dịch", "greetmed", "kim bướm"],
    specs: [
      { label: "Kích cỡ", value: "22G" },
      { label: "Chất liệu", value: "Nhựa y tế + kim thép" },
      { label: "Đặc điểm", value: "Vô trùng, dùng một lần" },
      { label: "Đóng gói", value: "1 cái / túi" },
    ],
  },
  {
    id: "omron-pad-replacement",
    name: "Miếng dán thay thế máy massage Omron HV-F013",
    slug: "mieng-dan-thay-the-may-massage-omron-hv-f013",
    price: 145000,
    unit: "Bộ",
    category: "Thiết bị hỗ trợ trị liệu",
    accent: "#8caecc",
    imagePath: "/omron_1.webp",
    imageAlt: "Miếng dán thay thế máy massage Omron",
    description: "Bộ miếng dán thay thế giúp duy trì hiệu quả truyền xung điện khi chăm sóc cơ bắp tại nhà.",
    shortDescription: "Miếng dán thay thế cho máy massage xung điện Omron.",
    rating: 4.6,
    reviewCount: 34,
    tags: ["massage", "trị liệu", "omron"],
    specs: [
      { label: "Loại", value: "Miếng dán thay thế" },
      { label: "Phù hợp", value: "Máy Omron HV-F013" },
      { label: "Đóng gói", value: "1 bộ" },
      { label: "Bảo quản", value: "Túi kín sau khi dùng" },
    ],
  },
  {
    id: "omron-lead-wire",
    name: "Dây dẫn xung điện Omron cho máy trị liệu",
    slug: "day-dan-xung-dien-omron-cho-may-tri-lieu",
    price: 180000,
    unit: "Cái",
    category: "Thiết bị hỗ trợ trị liệu",
    accent: "#8caecc",
    imagePath: "/omron_2.webp",
    imageAlt: "Dây dẫn xung điện Omron",
    description: "Dây dẫn thay thế cho thiết bị trị liệu xung điện, đầu cắm chắc chắn và dễ lắp đặt.",
    shortDescription: "Dây dẫn thay thế cho thiết bị trị liệu xung điện.",
    rating: 4.5,
    reviewCount: 28,
    tags: ["massage", "phụ kiện", "omron"],
    specs: [
      { label: "Chất liệu", value: "Dây bọc nhựa mềm" },
      { label: "Ứng dụng", value: "Dẫn xung điện trị liệu" },
      { label: "Đóng gói", value: "1 dây" },
      { label: "Phù hợp", value: "Thiết bị Omron tương thích" },
    ],
  },
  {
    id: "greentec-child-mask",
    name: "Mặt nạ xông khí dung Greentec trẻ em size S",
    slug: "mat-na-xong-khi-dung-greentec-tre-em-size-s",
    price: 19000,
    unit: "Cái",
    category: "Phụ kiện khí dung",
    accent: "#85e6f4",
    imagePath: "/greatmed_1.webp",
    imageAlt: "Mặt nạ khí dung Greentec trẻ em",
    description: "Mặt nạ khí dung size nhỏ, chất liệu mềm, giúp trẻ sử dụng máy xông thoải mái hơn.",
    shortDescription: "Mặt nạ khí dung size S dành cho trẻ em.",
    rating: 4.7,
    reviewCount: 47,
    tags: ["khí dung", "trẻ em", "greentec"],
    specs: [
      { label: "Kích cỡ", value: "Size S" },
      { label: "Đối tượng", value: "Trẻ em" },
      { label: "Chất liệu", value: "Nhựa y tế mềm" },
      { label: "Đóng gói", value: "1 cái / túi" },
    ],
  },
  {
    id: "greentec-nebulizer-tube",
    name: "Dây dẫn khí dung Greentec dài 2m",
    slug: "day-dan-khi-dung-greentec-dai-2m",
    price: 25000,
    unit: "Cái",
    category: "Phụ kiện khí dung",
    accent: "#85e6f4",
    imagePath: "/greatmed_2.webp",
    imageAlt: "Dây dẫn khí dung Greentec",
    description: "Dây dẫn khí mềm, dùng kết nối máy xông khí dung với cốc thuốc và mặt nạ.",
    shortDescription: "Dây dẫn khí dung mềm, dễ lắp và dễ vệ sinh.",
    rating: 4.4,
    reviewCount: 39,
    tags: ["khí dung", "phụ kiện", "greentec"],
    specs: [
      { label: "Chiều dài", value: "2m" },
      { label: "Chất liệu", value: "PVC y tế" },
      { label: "Ứng dụng", value: "Máy xông khí dung" },
      { label: "Đóng gói", value: "1 dây" },
    ],
  },
  {
    id: "insupen-32g-4mm",
    name: "Đầu kim tiểu đường Pic Insupen 32G x 4mm",
    slug: "dau-kim-tieu-duong-pic-insupen-32g-4mm",
    price: 235000,
    unit: "Hộp",
    category: "Chăm sóc tiểu đường",
    accent: "#f5ca5e",
    imagePath: "/DSC_1.webp",
    imageAlt: "Đầu kim tiểu đường Pic Insupen 32G",
    description: "Đầu kim tiêm insulin thành mỏng, phù hợp người cần kiểm soát đường huyết hằng ngày.",
    shortDescription: "Đầu kim insulin 32G dùng một lần, vô trùng.",
    rating: 4.8,
    reviewCount: 88,
    tags: ["tiểu đường", "insulin", "pic"],
    specs: [
      { label: "Kích cỡ", value: "32G x 4mm" },
      { label: "Đóng gói", value: "100 kim / hộp" },
      { label: "Đặc điểm", value: "Thành kim mỏng" },
      { label: "Ứng dụng", value: "Bút tiêm insulin" },
    ],
  },
  {
    id: "insupen-31g-6mm",
    name: "Đầu kim tiểu đường Pic Insupen 31G x 6mm",
    slug: "dau-kim-tieu-duong-pic-insupen-31g-6mm",
    price: 225000,
    unit: "Hộp",
    category: "Chăm sóc tiểu đường",
    accent: "#f5ca5e",
    imagePath: "/DSC_2.webp",
    imageAlt: "Đầu kim tiểu đường Pic Insupen 31G",
    description: "Đầu kim insulin vô trùng với chiều dài 6mm, dễ thao tác cho người dùng tại nhà.",
    shortDescription: "Đầu kim insulin 31G x 6mm cho bút tiêm hằng ngày.",
    rating: 4.7,
    reviewCount: 64,
    tags: ["tiểu đường", "insulin", "pic"],
    specs: [
      { label: "Kích cỡ", value: "31G x 6mm" },
      { label: "Đóng gói", value: "100 kim / hộp" },
      { label: "Tiêu chuẩn", value: "Vô trùng" },
      { label: "Đối tượng", value: "Người dùng insulin" },
    ],
  },
  {
    id: "yuwell-ye660e",
    name: "Máy đo huyết áp bắp tay Yuwell YE660E",
    slug: "may-do-huyet-ap-yuwell-ye660e",
    price: 790000,
    unit: "Hộp",
    category: "Máy đo huyết áp",
    accent: "#d7dfe7",
    imagePath: "/TUK_2.webp",
    imageAlt: "Máy đo huyết áp Yuwell YE660E",
    description: "Máy đo huyết áp tự động có bộ nhớ kết quả, phù hợp theo dõi sức khỏe gia đình.",
    shortDescription: "Máy đo huyết áp tự động, màn hình lớn, dễ đọc.",
    rating: 4.7,
    reviewCount: 97,
    tags: ["huyết áp", "yuwell", "điện tử"],
    specs: [
      { label: "Vị trí đo", value: "Bắp tay" },
      { label: "Nguồn", value: "Pin / Adapter" },
      { label: "Màn hình", value: "LCD lớn" },
      { label: "Tính năng", value: "Lưu kết quả" },
    ],
  },
  {
    id: "yuwell-wrist-bp",
    name: "Máy đo huyết áp cổ tay Yuwell YE8900A",
    slug: "may-do-huyet-ap-co-tay-yuwell-ye8900a",
    price: 620000,
    unit: "Hộp",
    category: "Máy đo huyết áp",
    accent: "#d7dfe7",
    imagePath: "/TUK_3.webp",
    imageAlt: "Máy đo huyết áp cổ tay Yuwell",
    description: "Thiết bị đo huyết áp cổ tay gọn nhẹ, tiện mang theo khi đi làm hoặc đi du lịch.",
    shortDescription: "Máy đo huyết áp cổ tay nhỏ gọn, thao tác nhanh.",
    rating: 4.5,
    reviewCount: 58,
    tags: ["huyết áp", "cổ tay", "yuwell"],
    specs: [
      { label: "Vị trí đo", value: "Cổ tay" },
      { label: "Thiết kế", value: "Nhỏ gọn" },
      { label: "Nguồn", value: "Pin AAA" },
      { label: "Phù hợp", value: "Theo dõi cá nhân" },
    ],
  },
  {
    id: "yuwell-yt2c",
    name: "Nhiệt kế hồng ngoại Yuwell YT-2C",
    slug: "nhiet-ke-hong-ngoai-yuwell-yt2c",
    price: 560000,
    unit: "Hộp",
    category: "Nhiệt kế",
    accent: "#dfe7ee",
    imagePath: "/NKHN_1.webp",
    imageAlt: "Nhiệt kế hồng ngoại Yuwell YT-2C",
    description: "Nhiệt kế hồng ngoại đo trán không tiếp xúc, có cảnh báo sốt bằng màu đèn nền.",
    shortDescription: "Nhiệt kế không chạm, trả kết quả nhanh trong 1 giây.",
    rating: 4.6,
    reviewCount: 72,
    tags: ["nhiệt kế", "hồng ngoại", "yuwell"],
    specs: [
      { label: "Kiểu đo", value: "Không tiếp xúc" },
      { label: "Thời gian", value: "1 giây" },
      { label: "Nguồn", value: "Pin AAA" },
      { label: "Cảnh báo", value: "Đèn nền màu" },
    ],
  },
  {
    id: "infrared-family-kit",
    name: "Bộ nhiệt kế hồng ngoại gia đình Yuwell",
    slug: "bo-nhiet-ke-hong-ngoai-gia-dinh-yuwell",
    price: 610000,
    unit: "Bộ",
    category: "Nhiệt kế",
    accent: "#dfe7ee",
    imagePath: "/NKHN_2.webp",
    imageAlt: "Bộ nhiệt kế hồng ngoại gia đình Yuwell",
    description: "Bộ nhiệt kế kèm hộp bảo quản, phù hợp theo dõi nhiệt độ cho trẻ em và người lớn.",
    shortDescription: "Bộ nhiệt kế hồng ngoại kèm hộp bảo quản tiện dụng.",
    rating: 4.7,
    reviewCount: 69,
    tags: ["nhiệt kế", "gia đình", "yuwell"],
    specs: [
      { label: "Kiểu đo", value: "Không chạm" },
      { label: "Phụ kiện", value: "Hộp bảo quản" },
      { label: "Đối tượng", value: "Gia đình" },
      { label: "Nguồn", value: "Pin AAA" },
    ],
  },
  {
    id: "lancet-30g",
    name: "Kim lấy máu Lancet Medicleen 30G",
    slug: "kim-lay-mau-lancet-medicleen-30g",
    price: 36000,
    unit: "Hộp",
    category: "Tiêu hao y tế",
    accent: "#8ea8d2",
    imagePath: "/KLM_1.webp",
    imageAlt: "Kim lấy máu Lancet Medicleen 30G",
    description: "Kim lấy máu đầu nhỏ, dùng một lần cho thiết bị đo đường huyết cá nhân.",
    shortDescription: "Kim lấy máu 30G dùng một lần, hạn chế đau rát.",
    rating: 4.6,
    reviewCount: 44,
    tags: ["lancet", "lấy máu", "tiêu hao"],
    specs: [
      { label: "Chuẩn kim", value: "30G" },
      { label: "Đóng gói", value: "100 chiếc / hộp" },
      { label: "Tiêu chuẩn", value: "Vô trùng" },
      { label: "Ứng dụng", value: "Lấy máu mao mạch" },
    ],
  },
  {
    id: "lancet-28g-blue",
    name: "Kim lấy máu Lancet BL-28 xanh",
    slug: "kim-lay-mau-lancet-bl28-xanh",
    price: 33000,
    unit: "Hộp",
    category: "Tiêu hao y tế",
    accent: "#8ea8d2",
    imagePath: "/KLM_2.webp",
    imageAlt: "Kim lấy máu Lancet BL-28 xanh",
    description: "Kim lancet vô trùng, thiết kế đầu vát giúp lấy mẫu máu nhanh và ổn định.",
    shortDescription: "Kim lancet BL-28 dùng kèm bút lấy máu.",
    rating: 4.5,
    reviewCount: 37,
    tags: ["lancet", "lấy máu", "tiêu hao"],
    specs: [
      { label: "Chuẩn kim", value: "BL-28" },
      { label: "Màu", value: "Xanh" },
      { label: "Đóng gói", value: "100 chiếc / hộp" },
      { label: "Loại", value: "Dùng một lần" },
    ],
  },
  {
    id: "braun-20g",
    name: "Kim luồn tĩnh mạch Braun 20G",
    slug: "kim-luon-tinh-mach-braun-20g",
    price: 21000,
    unit: "Cái",
    category: "Tiêu hao y tế",
    accent: "#dce8f5",
    imagePath: "/Braun_1.webp",
    imageAlt: "Kim luồn tĩnh mạch Braun 20G",
    description: "Kim luồn vô trùng kích cỡ 20G, dùng trong môi trường y tế theo chỉ định chuyên môn.",
    shortDescription: "Kim luồn tĩnh mạch Braun 20G, vô trùng, dùng một lần.",
    rating: 4.4,
    reviewCount: 24,
    tags: ["kim luồn", "braun", "truyền dịch"],
    specs: [
      { label: "Kích cỡ", value: "20G" },
      { label: "Loại", value: "Vô trùng" },
      { label: "Ứng dụng", value: "Truyền dịch ngoại vi" },
      { label: "Đóng gói", value: "1 cái / túi" },
    ],
  },
  {
    id: "accu-chek-strips-50",
    name: "Que thử đường huyết Accu-Chek Instant 50 que",
    slug: "que-thu-duong-huyet-accu-chek-instant-50-que",
    price: 390000,
    unit: "Hộp",
    category: "Chăm sóc tiểu đường",
    accent: "#d7ecff",
    imagePath: "/Accu_1.webp",
    imageAlt: "Que thử đường huyết Accu-Chek Instant",
    description: "Que thử dùng cùng máy Accu-Chek Instant, hỗ trợ theo dõi đường huyết tại nhà.",
    shortDescription: "Que thử đường huyết Accu-Chek hộp 50 que.",
    rating: 4.9,
    reviewCount: 134,
    tags: ["đường huyết", "accu-chek", "tiểu đường"],
    specs: [
      { label: "Đóng gói", value: "50 que / hộp" },
      { label: "Tương thích", value: "Accu-Chek Instant" },
      { label: "Ứng dụng", value: "Đo đường huyết" },
      { label: "Bảo quản", value: "Đóng nắp sau khi lấy" },
    ],
  },
  {
    id: "accu-chek-lancet-kit",
    name: "Bộ kim và bút lấy máu Accu-Chek",
    slug: "bo-kim-va-but-lay-mau-accu-chek",
    price: 210000,
    unit: "Bộ",
    category: "Chăm sóc tiểu đường",
    accent: "#d7ecff",
    imagePath: "/Accu_2.webp",
    imageAlt: "Bộ kim và bút lấy máu Accu-Chek",
    description: "Bộ bút lấy máu và kim đi kèm, hỗ trợ lấy mẫu nhanh cho người cần đo đường huyết.",
    shortDescription: "Bộ bút lấy máu Accu-Chek kèm kim dùng một lần.",
    rating: 4.7,
    reviewCount: 73,
    tags: ["đường huyết", "accu-chek", "lấy máu"],
    specs: [
      { label: "Thành phần", value: "Bút lấy máu + kim" },
      { label: "Ứng dụng", value: "Lấy mẫu máu mao mạch" },
      { label: "Đối tượng", value: "Người theo dõi đường huyết" },
      { label: "Đóng gói", value: "1 bộ" },
    ],
  },
  {
    id: "butterfly-23g",
    name: "Dây truyền dịch kim bướm Greetmed 23G",
    slug: "day-truyen-dich-kim-buom-greetmed-23g",
    price: 6000,
    unit: "Cái",
    category: "Tiêu hao y tế",
    accent: "#eff5fb",
    imagePath: "/DTD_1.webp",
    imageAlt: "Dây truyền dịch kim bướm Greetmed 23G",
    description: "Dây kim bướm 23G vô trùng, hỗ trợ thao tác lấy ven và truyền dịch ngắn hạn.",
    shortDescription: "Dây kim bướm 23G vô trùng, dùng một lần.",
    rating: 4.3,
    reviewCount: 22,
    tags: ["truyền dịch", "greetmed", "kim bướm"],
    specs: [
      { label: "Kích cỡ", value: "23G" },
      { label: "Loại", value: "Vô trùng" },
      { label: "Đóng gói", value: "1 cái / túi" },
      { label: "Ứng dụng", value: "Truyền dịch ngắn hạn" },
    ],
  },
  {
    id: "butterfly-24g",
    name: "Dây truyền dịch kim bướm Greetmed 24G",
    slug: "day-truyen-dich-kim-buom-greetmed-24g",
    price: 6500,
    unit: "Cái",
    category: "Tiêu hao y tế",
    accent: "#eff5fb",
    imagePath: "/DTD_2.webp",
    imageAlt: "Dây truyền dịch kim bướm Greetmed 24G",
    description: "Dây kim bướm kích cỡ nhỏ, phù hợp thao tác cần kim mảnh trong môi trường y tế.",
    shortDescription: "Dây kim bướm 24G mảnh, vô trùng, dùng một lần.",
    rating: 4.2,
    reviewCount: 18,
    tags: ["truyền dịch", "greetmed", "kim bướm"],
    specs: [
      { label: "Kích cỡ", value: "24G" },
      { label: "Loại", value: "Dùng một lần" },
      { label: "Chất liệu", value: "PVC y tế + kim thép" },
      { label: "Đóng gói", value: "1 cái / túi" },
    ],
  },
  {
    id: "family-care-combo",
    name: "Combo chăm sóc sức khỏe gia đình MediCare",
    slug: "combo-cham-soc-suc-khoe-gia-dinh-medicare",
    price: 1290000,
    unit: "Bộ",
    category: "Combo chăm sóc",
    accent: "#b8d8f4",
    imagePath: "/Accu_3.webp",
    imageAlt: "Combo chăm sóc sức khỏe gia đình MediCare",
    description: "Combo gồm thiết bị theo dõi sức khỏe cơ bản, phù hợp tủ thuốc gia đình hiện đại.",
    shortDescription: "Combo thiết bị theo dõi sức khỏe cơ bản cho gia đình.",
    rating: 4.8,
    reviewCount: 56,
    tags: ["combo", "gia đình", "đường huyết"],
    specs: [
      { label: "Thành phần", value: "Thiết bị theo dõi sức khỏe" },
      { label: "Đối tượng", value: "Gia đình" },
      { label: "Ưu điểm", value: "Tiện mua theo bộ" },
      { label: "Bảo quản", value: "Nơi khô ráo" },
    ],
  },
  {
    id: "therapy-home-combo",
    name: "Combo trị liệu cơ xương khớp tại nhà",
    slug: "combo-tri-lieu-co-xuong-khop-tai-nha",
    price: 1380000,
    unit: "Bộ",
    category: "Combo chăm sóc",
    accent: "#8caecc",
    imagePath: "/omron_3.webp",
    imageAlt: "Combo trị liệu cơ xương khớp tại nhà",
    description: "Combo thiết bị và phụ kiện trị liệu giúp chăm sóc vùng cơ mỏi sau vận động hoặc làm việc.",
    shortDescription: "Combo chăm sóc cơ xương khớp tại nhà.",
    rating: 4.7,
    reviewCount: 49,
    tags: ["combo", "massage", "trị liệu"],
    specs: [
      { label: "Thành phần", value: "Máy trị liệu + phụ kiện" },
      { label: "Phù hợp", value: "Người đau mỏi cơ" },
      { label: "Ứng dụng", value: "Chăm sóc tại nhà" },
      { label: "Bảo hành", value: "Theo từng sản phẩm" },
    ],
  },
  {
    id: "respiratory-care-combo",
    name: "Combo phụ kiện khí dung gia đình",
    slug: "combo-phu-kien-khi-dung-gia-dinh",
    price: 125000,
    unit: "Bộ",
    category: "Combo chăm sóc",
    accent: "#85e6f4",
    imagePath: "/greatmed_3.webp",
    imageAlt: "Combo phụ kiện khí dung gia đình",
    description: "Bộ phụ kiện khí dung gồm mặt nạ và dây dẫn thay thế, hỗ trợ vệ sinh thiết bị định kỳ.",
    shortDescription: "Combo mặt nạ và dây dẫn khí dung thay thế.",
    rating: 4.5,
    reviewCount: 33,
    tags: ["combo", "khí dung", "phụ kiện"],
    specs: [
      { label: "Thành phần", value: "Mặt nạ + dây dẫn" },
      { label: "Đối tượng", value: "Gia đình" },
      { label: "Ứng dụng", value: "Máy xông khí dung" },
      { label: "Đóng gói", value: "1 bộ" },
    ],
  },
  {
    id: "diabetes-care-combo",
    name: "Combo chăm sóc tiểu đường Accu-Chek",
    slug: "combo-cham-soc-tieu-duong-accu-chek",
    price: 1190000,
    unit: "Bộ",
    category: "Combo chăm sóc",
    accent: "#d7ecff",
    imagePath: "/Accu_4.webp",
    imageAlt: "Combo chăm sóc tiểu đường Accu-Chek",
    description: "Combo máy đo, que thử và phụ kiện lấy máu cho người cần theo dõi đường huyết hằng ngày.",
    shortDescription: "Combo theo dõi đường huyết tại nhà cho người tiểu đường.",
    rating: 4.9,
    reviewCount: 102,
    tags: ["combo", "đường huyết", "accu-chek"],
    specs: [
      { label: "Thành phần", value: "Máy đo + que thử + phụ kiện" },
      { label: "Đối tượng", value: "Người theo dõi đường huyết" },
      { label: "Ứng dụng", value: "Chăm sóc tại nhà" },
      { label: "Bảo quản", value: "Tránh ẩm" },
    ],
  },
  {
    id: "sterile-gauze-10x10",
    name: "Gạc vô trùng MediCare 10 x 10cm",
    slug: "gac-vo-trung-medicare-10x10cm",
    price: 45000,
    unit: "Hộp",
    category: "Tiêu hao y tế",
    accent: "#dce8f5",
    imagePath: "/KLM_3.webp",
    imageAlt: "Gạc vô trùng MediCare 10 x 10cm",
    description: "Gạc y tế vô trùng dùng che phủ, vệ sinh và chăm sóc vết thương theo hướng dẫn.",
    shortDescription: "Gạc vô trùng 10 x 10cm cho tủ thuốc gia đình.",
    rating: 4.5,
    reviewCount: 61,
    tags: ["gạc", "tiêu hao", "vết thương"],
    specs: [
      { label: "Kích thước", value: "10 x 10cm" },
      { label: "Loại", value: "Vô trùng" },
      { label: "Đóng gói", value: "Hộp nhiều miếng" },
      { label: "Ứng dụng", value: "Chăm sóc vết thương" },
    ],
  },
  {
    id: "medical-tape-2-5",
    name: "Băng keo y tế MediCare 2.5cm",
    slug: "bang-keo-y-te-medicare-2-5cm",
    price: 18000,
    unit: "Cuộn",
    category: "Tiêu hao y tế",
    accent: "#dce8f5",
    imagePath: "/KLM_4.webp",
    imageAlt: "Băng keo y tế MediCare 2.5cm",
    description: "Băng keo y tế mềm, độ bám tốt, dùng cố định gạc và vật tư chăm sóc vết thương.",
    shortDescription: "Băng keo y tế 2.5cm dùng cố định gạc.",
    rating: 4.4,
    reviewCount: 42,
    tags: ["băng keo", "tiêu hao", "vết thương"],
    specs: [
      { label: "Khổ rộng", value: "2.5cm" },
      { label: "Loại", value: "Cuộn" },
      { label: "Ứng dụng", value: "Cố định gạc" },
      { label: "Chất liệu", value: "Vải không dệt" },
    ],
  },
  {
    id: "alcohol-swab-box",
    name: "Bông tẩm cồn sát khuẩn MediCare",
    slug: "bong-tam-con-sat-khuan-medicare",
    price: 52000,
    unit: "Hộp",
    category: "Tiêu hao y tế",
    accent: "#dce8f5",
    imagePath: "/DSC_3.webp",
    imageAlt: "Bông tẩm cồn sát khuẩn MediCare",
    description: "Miếng bông tẩm cồn đóng gói riêng, hỗ trợ sát khuẩn trước khi lấy mẫu hoặc tiêm.",
    shortDescription: "Bông tẩm cồn đóng gói riêng, tiện dùng hằng ngày.",
    rating: 4.6,
    reviewCount: 55,
    tags: ["sát khuẩn", "tiêu hao", "tiểu đường"],
    specs: [
      { label: "Đóng gói", value: "Hộp nhiều miếng" },
      { label: "Ứng dụng", value: "Sát khuẩn da" },
      { label: "Tiện ích", value: "Gói riêng từng miếng" },
      { label: "Bảo quản", value: "Đậy kín, tránh nhiệt" },
    ],
  },
  {
    id: "pulse-oximeter-fingertip",
    name: "Máy đo SpO2 đầu ngón tay MediCare",
    slug: "may-do-spo2-dau-ngon-tay-medicare",
    price: 390000,
    unit: "Hộp",
    category: "Thiết bị hỗ trợ trị liệu",
    accent: "#b8d8f4",
    imagePath: "/NKHN_3.webp",
    imageAlt: "Máy đo SpO2 đầu ngón tay MediCare",
    description: "Thiết bị đo SpO2 và nhịp tim đầu ngón tay, màn hình rõ nét và thao tác đơn giản.",
    shortDescription: "Máy đo SpO2 đầu ngón tay, nhỏ gọn và dễ dùng.",
    rating: 4.6,
    reviewCount: 81,
    tags: ["spo2", "theo dõi", "gia đình"],
    specs: [
      { label: "Chỉ số", value: "SpO2, nhịp tim" },
      { label: "Nguồn", value: "Pin AAA" },
      { label: "Màn hình", value: "OLED" },
      { label: "Phù hợp", value: "Theo dõi tại nhà" },
    ],
  },
];

export const productDetailContent: Record<string, ProductDetailContent> = {
  "omron-hvf013": {
    gallery: [
      "/omron_main.webp",
      "/omron_1.webp",
      "/omron_2.webp",
      "/omron_3.webp",
      "/omron_4.webp",
    ],
    summary: [
      "Công nghệ TENS giảm đau hiệu quả",
      "5 chế độ trị liệu chuyên sâu",
      "10 mức cường độ linh hoạt",
      "Nguồn điện pin AAA",
    ],
    description:
      "Omron HV-F013 là giải pháp chăm sóc cơ xương khớp không xâm lấn, phù hợp với người thường xuyên đau mỏi, chơi thể thao, làm việc văn phòng hoặc người lớn tuổi. Sản phẩm hỗ trợ thư giãn cơ, cải thiện lưu thông máu và nâng chất lượng chăm sóc sức khỏe tại nhà.",
    uses:
      "Máy xung điện trị liệu sử dụng công nghệ TENS để kích thích thần kinh qua da, hỗ trợ chặn tín hiệu đau, kích hoạt endorphin tự nhiên và cải thiện lưu thông máu nhờ co giãn cơ lặp lại.",
    usage: "Dán miếng pad lên vùng cần trị liệu, chọn chế độ phù hợp và tăng cường độ từ mức thấp.",
    cautions:
      "Không sử dụng với thiết bị y tế cấy ghép, cho trẻ em, người mang thai, vùng đầu mặt cổ, vết thương hở hoặc vùng da mất cảm giác bình thường.",
    storage: "Bảo quản nơi khô ráo, tránh nhiệt độ cao và vệ sinh miếng pad sau khi dùng.",
  },
  "greentec-mask": {
    gallery: ["/greatmed_main.webp", "/greatmed_1.webp", "/greatmed_2.webp"],
    summary: ["Chất liệu an toàn", "Thiết kế vừa vặn khuôn mặt", "Dễ vệ sinh"],
    description:
      "Mặt nạ xông khí dung Greetmed size M giúp người bệnh hấp thu dung dịch xông hiệu quả và dễ dàng hơn. Thiết kế có chốt điều chỉnh ở mũi, tạo cảm giác thoải mái khi dùng aerosol.",
    uses:
      "Dùng kèm máy khí dung để đưa dung dịch xông vào khoang mũi và đường hô hấp theo hướng dẫn chuyên môn.",
    usage: "Lắp mặt nạ vào dây dẫn khí dung, đặt ôm kín vùng mũi miệng và dùng theo chỉ dẫn của nhân viên y tế.",
    cautions: "Không dùng chung để tránh lây nhiễm. Kiểm tra tình trạng mặt nạ trước khi sử dụng.",
    storage: "Bảo quản nơi khô ráo, thoáng mát, tránh ánh sáng trực tiếp và để xa tầm tay trẻ em.",
  },
  "pic-insupen": {
    gallery: ["/DSC_main.webp", "/DSC_1.webp", "/DSC_2.webp", "/DSC_3.webp", "/DSC_4.webp"],
    summary: [
      "Đầu kim siêu mảnh",
      "Ít gây đau",
      "Dùng một lần an toàn",
      "Hộp 100 kim",
    ],
    description:
      "Đầu kim tiểu đường Insupen sử dụng công nghệ giảm đau, đường kính ngoài nhỏ, thành kim mỏng và bề mặt được xử lý bôi trơn để thao tác tiêm thoải mái hơn.",
    uses: "Lắp cùng bút tiêm insulin cho người bệnh tiểu đường.",
    usage:
      "Luôn lắp kim mới trước mỗi lần tiêm, kiểm tra thuốc chảy đúng cách, nhấn hết nút tiêm và giữ kim đủ lâu trước khi rút ra.",
    cautions:
      "Không tái sử dụng kim, không cất bút khi còn gắn kim và bỏ kim sau tiêm vào hộp chứa phù hợp.",
    storage: "Để nơi sạch sẽ, khô ráo, thoáng mát.",
  },
  "yuwell-ye610d": {
    gallery: ["/TUK_1.webp", "/TUK_2.webp", "/TUK_3.webp"],
    summary: ["Đo nhanh và chính xác", "Màn hình lớn dễ đọc", "Tự động hoàn toàn"],
    description:
      "Máy đo huyết áp điện tử bắp tay Yuwell YE610D cho phép kiểm tra huyết áp chỉ với một nút bấm, lưu trữ nhiều kết quả và hỗ trợ theo dõi sức khỏe tại nhà.",
    uses: "Dùng để đo huyết áp tâm thu, huyết áp tâm trương và nhịp tim.",
    usage: "Đeo vòng bít đúng vị trí, ngồi yên và bấm nút đo.",
    cautions:
      "Ngồi nghỉ 5 phút trước khi đo, không đo ngay sau khi vận động, hút thuốc, uống rượu bia, cà phê hoặc trà.",
    storage: "Nơi khô ráo, thoáng mát.",
  },
  "infrared-nc1": {
    gallery: ["/NKHN_main.webp", "/NKHN_1.webp", "/NKHN_2.webp", "/NKHN_3.webp"],
    summary: ["Đo nhanh 1 giây", "Không tiếp xúc", "An toàn cho trẻ em"],
    description:
      "Nhiệt kế hồng ngoại Yuwell YT-1C dùng cảm biến hồng ngoại để đo nhiệt độ không tiếp xúc, có cảnh báo sốt và đèn nền đổi màu.",
    uses: "Dùng để đo nhiệt độ trán người dùng và nhiệt độ môi trường xung quanh.",
    usage:
      "Lắp pin đúng cực, chọn chế độ đo cơ thể hoặc vật thể, đưa nhiệt kế vào vùng trán theo khoảng cách hướng dẫn và bấm đo.",
    cautions: "Không đo khi trán ướt hoặc ngay sau khi vận động mạnh.",
    storage: "Tránh ánh nắng trực tiếp và nơi ẩm.",
  },
  "lancet-medi": {
    gallery: ["/KLM_main.webp", "/KLM_1.webp", "/KLM_2.webp", "/KLM_3.webp", "/KLM_4.webp"],
    summary: ["Đầu kim vát ba cạnh", "Tiệt trùng sẵn", "Dùng một lần"],
    description:
      "Kim lấy máu Lancet Medicleen BL-28G là kim lấy máu đầu vặn, đầu vát ba cạnh giúp lấy mẫu ít đau và thao tác nhanh.",
    uses: "Dùng với bút lấy máu để lấy lượng máu nhỏ phục vụ kiểm tra chỉ số.",
    usage:
      "Lắp kim vào bút lấy máu, đóng nắp bảo vệ, thao tác theo hướng dẫn của bút và bỏ kim vào thùng chứa sau khi dùng.",
    cautions: "Không dùng kim nếu đầu bảo vệ bị mất hoặc lỏng.",
    storage: "Giữ trong bao bì kín.",
  },
  "braun-22g": {
    gallery: ["/Braun_1.webp"],
    summary: ["Chất lượng cao", "Vô trùng", "Dùng trong môi trường y tế"],
    description:
      "Kim luồn tĩnh mạch Braun 22G là thiết bị tiêu hao y tế hỗ trợ truyền dịch, thuốc và dinh dưỡng vào cơ thể.",
    uses: "Dùng trong truyền dịch hoặc điều trị theo chỉ định y tế.",
    usage: "Do nhân viên y tế thực hiện.",
    cautions: "Không tự ý sử dụng tại nhà khi không có chuyên môn.",
    storage: "Giữ vô trùng và bảo quản theo hướng dẫn trên bao bì.",
  },
  "accu-chek-instant": {
    gallery: ["/Accu_main.webp", "/Accu_1.webp", "/Accu_2.webp", "/Accu_3.webp", "/Accu_4.webp"],
    summary: ["Đo nhanh", "Chính xác cao", "Dễ sử dụng", "Có kết nối Bluetooth"],
    description:
      "Máy đo đường huyết Accu-Chek Instant hỗ trợ định lượng đường huyết mao mạch, giúp người bệnh theo dõi và kiểm soát đường huyết hằng ngày.",
    uses: "Theo dõi đường huyết tại nhà theo hướng dẫn chuyên môn.",
    usage: "Sử dụng que thử đúng cách, lấy mẫu máu đầu ngón tay và đọc kết quả trên màn hình.",
    cautions: "Không dùng que thử quá hạn hoặc que thử bị ẩm.",
    storage: "Tránh ẩm, đóng nắp lọ que thử ngay sau khi lấy.",
  },
  "greetmed-butterfly-22g": {
    gallery: ["/DTD_main.webp", "/DTD_1.webp", "/DTD_2.webp", "/DTD_3.webp"],
    summary: ["Thiết kế linh hoạt", "Dễ sử dụng", "Vô trùng dùng một lần"],
    description:
      "Dây truyền dịch kim cánh bướm Greetmed dùng vật liệu nhựa PVC mềm, trong suốt và kim truyền chắc chắn trong điều kiện sử dụng bình thường.",
    uses: "Dùng để truyền dịch hoặc lấy máu trong môi trường y tế.",
    usage: "Sử dụng theo quy trình của nhân viên y tế.",
    cautions: "Không tái sử dụng và không dùng nếu bao bì hở hoặc hư hỏng.",
    storage: "Giữ vô trùng, bảo quản nơi khô ráo.",
  },
};

export const featuredProductIds = [
  "omron-hvf013",
  "greentec-mask",
  "pic-insupen",
  "yuwell-ye610d",
  "infrared-nc1",
  "lancet-medi",
  "braun-22g",
  "accu-chek-instant",
  "greetmed-butterfly-22g",
] as const;

export function getFeaturedProducts() {
  return featuredProductIds
    .map((id) => products.find((product) => product.id === id))
    .filter((product): product is Product => Boolean(product));
}

export function getProductById(id: string) {
  return products.find((product) => product.id === id);
}

export function getProductBySlug(slug: string) {
  return products.find((product) => product.slug === slug);
}

export function getProductDetailContent(productId: string) {
  return productDetailContent[productId];
}

export function getRelatedProducts(productId: string) {
  const currentProduct = getProductById(productId);

  if (!currentProduct) {
    return [];
  }

  return products
    .filter(
      (product) =>
        product.id !== productId &&
        (product.category === currentProduct.category ||
          product.tags.some((tag) => currentProduct.tags.includes(tag))),
    )
    .slice(0, 3);
}
